name: Android CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Key from Secrets
        env:
          google_map_key: ${{ secrets.API_KEY }}
          kakao_api_key: ${{ secrets.KAKAO_API_KEY }}
        run:
          echo -e google_map_key="$google_map_key" >> ./local.properties
          echo -e kakao_api_key="$kakao_api_key" >> ./local.properties

      - name: Get KeyStore from Secrets
        env:
          storePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          storeFile: ${{ secrets.STORE_FILE }}
        run:
          echo -e storePassword="$storePassword"\n
          keyPassword="$keyPassword"\n
          keyAlias="$keyAlias" > ./keystore.properties

      - name: print ls
        run: ls

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
