name: Android CI

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get Key from Secrets
        env:
          google_map_key: ${{ secrets.API_KEY }}
        run: echo google_map_key="$google_map_key" > ./local.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
